# Generated by Django 6.1.1 on 2026-09-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingguest',
            name='attending',
            field=models.BooleanField(choices=[('PENDING', 'Моля, изберете...'), ('YES', 'С удоволствие ще присъствам'), ('NO', 'За съжаление няма да мога')], default='PENDING', null=True),
        ),
    ]
